WTSC <- WTSC %>%
  mutate(agency.wstc = case_when(
    repjur == 1 ~ "WSP-3"
    repjur == 2 ~ "WSP-7"
    repjur == 3 ~ "WSP-1"
    repjur == 4 ~ "WSP-4"
    repjur == 5 ~ "WSP-5"
    repjur == 6 ~ "WSP-6"
    repjur == 7 ~ "WSP-2"
    repjur == 8 ~ "WSP-8"
    repjur == 9 ~ "Adams County"
    repjur == 10 ~ "Asotin County"
    repjur == 11 ~ "Benton County"
    repjur == 12 ~ "Chelan County"
    repjur == 13 ~ "Clallam County"
    repjur == 14 ~ "Clark County"
    repjur == 15 ~ "Columbia County"
    repjur == 16 ~ "Cowlitz County"
    repjur == 17 ~ "Douglas County"
    repjur == 18 ~ "Ferry County"
    repjur == 19 ~ "Franklin County"
    repjur == 20 ~ "Garfield County"
    repjur == 21 ~ "Grant County"
    repjur == 22 ~ "Grays Harbor County"
    repjur == 23 ~ "Island County"
    repjur == 24 ~ "Jefferson County"
    repjur == 25 ~ "King Co Dpt Pub Safe"
    repjur == 26 ~ "Kitsap County"
    repjur == 27 ~ "Kittitas County"
    repjur == 28 ~ "Klickitat County"
    repjur == 29 ~ "Lewis County"
    repjur == 30 ~ "Lincoln County"
    repjur == 31 ~ "Mason County"
    repjur == 32 ~ "Okanogan County"
    repjur == 33 ~ "Pacific County"
    repjur == 34 ~ "Pend Oreille County"
    repjur == 35 ~ "Pierce County"
    repjur == 36 ~ "San Juan County"
    repjur == 37 ~ "Skagit County"
    repjur == 38 ~ "Skamania County"
    repjur == 39 ~ "Snohomish County"
    repjur == 40 ~ "Spokane County"
    repjur == 41 ~ "Stevens County"
    repjur == 42 ~ "Thurston County"
    repjur == 43 ~ "Wahkiakum County"
    repjur == 44 ~ "Walla Walla County"
    repjur == 45 ~ "Whatcom County"
    repjur == 46 ~ "Whitman County"
    repjur == 47 ~ "Aberdeen Police Dept"
    repjur == 48 ~ "Airway Heights PD"
    repjur == 49 ~ "Albion PD"
    repjur == 50 ~ "Algona PD"
    repjur == 51 ~ "Almira Marshal"
    repjur == 52 ~ "Anacortes PD"
    repjur == 53 ~ "Arlington PD"
    repjur == 54 ~ "Asotin PD"
    repjur == 55 ~ "Auburn PD"
    repjur == 56 ~ "Bainbridge Isl PD"
    repjur == 57 ~ "Battle Ground PD"
    repjur == 58 ~ "Beaux Arts Village"
    repjur == 59 ~ "Bellevue PD"
    repjur == 60 ~ "Benton City PD"
    repjur == 61 ~ "Bickleton PD"
    repjur == 62 ~ "Bingen PD"
    repjur == 63 ~ "Black Diamond PD"
    repjur == 64 ~ "Blaine Dpt Pub Safet"
    repjur == 65 ~ "Bonney Lake PD"
    repjur == 66 ~ "Bothell PD"
    repjur == 67 ~ "Bremerton PD"
    repjur == 68 ~ "Brewster PD"
    repjur == 69 ~ "Bridgeport PD"
    repjur == 70 ~ "Brier PD"
    repjur == 71 ~ "Buckley PD"
    repjur == 72 ~ "Bucoda PD"
    repjur == 73 ~ "Burien PD"
    repjur == 74 ~ "Burlington PD"
    repjur == 75 ~ "Camas PD"
    repjur == 76 ~ "Carbonado PD"
    repjur == 77 ~ "Carnation PD"
    repjur == 78 ~ "Cashmere PD"
    repjur == 79 ~ "Castle Rock PD"
    repjur == 80 ~ "Cathlamet Marshal"
    repjur == 81 ~ "Central WA Univ"
    repjur == 82 ~ "Centralia PD"
    repjur == 83 ~ "Chehalis PD"
    repjur == 84 ~ "Chelan PD"
    repjur == 85 ~ "Cheney PD"
    repjur == 86 ~ "Chewelah PD"
    repjur == 87 ~ "Clarkston PD"
    repjur == 88 ~ "Cle Elum PD"
    repjur == 89 ~ "Clyde Hill PD"
    repjur == 90 ~ "Colfax PD"
    repjur == 91 ~ "College Place PD"
    repjur == 92 ~ "Colton PD"
    repjur == 93 ~ "Conconully Marshal"
    repjur == 94 ~ "Concrete PD"
    repjur == 95 ~ "Connel PD"
    repjur == 96 ~ "Cosmopolis PD"
    repjur == 97 ~ "Coulee City PD"
    repjur == 98 ~ "Coulee Dam PD"
    repjur == 99 ~ "Coupleville Marshal"
    repjur == 100 ~ "Creston PD"
    repjur == 101 ~ "Cusick PD"
    repjur == 102 ~ "Darrington PD"
    repjur == 103 ~ "Davenport PD"
    repjur == 104 ~ "Dayton PD"
    repjur == 105 ~ "Deer Park PD"
    repjur == 106 ~ "Des Moines PD"
    repjur == 107 ~ "Dupont PD"
    repjur == 108 ~ "Duvall PD"
    repjur == 109 ~ "E Wenatchee PD"
    repjur == 110 ~ "Eastern WA U PD"
    repjur == 111 ~ "Eatonville PD"
    repjur == 112 ~ "Edgewood PD"
    repjur == 113 ~ "Edmonds PD"
    repjur == 114 ~ "Electric City PD"
    repjur == 115 ~ "Ellensburg PD"
    repjur == 116 ~ "Elma PD"
    repjur == 117 ~ "Elmer City PD"
    repjur == 118 ~ "Endicott PD"
    repjur == 119 ~ "Entiat PD"
    repjur == 120 ~ "Enumclaw PD"
    repjur == 121 ~ "Ephrata PD"
    repjur == 122 ~ "Everett PD"
    repjur == 123 ~ "Evergreen St Col PD"
    repjur == 124 ~ "Everson PD"
    repjur == 125 ~ "Fair Field PD"
    repjur == 126 ~ "Farmington PD"
    repjur == 127 ~ "Federal Way Dpt Pub"
    repjur == 128 ~ "Ferndale PD"
    repjur == 129 ~ "Fife PD"
    repjur == 130 ~ "Fircrest PD"
    repjur == 131 ~ "Forks PD"
    repjur == 132 ~ "Friday Harbor PD"
    repjur == 133 ~ "Garfield PD"
    repjur == 134 ~ "George PD"
    repjur == 135 ~ "Gig Harbor PD"
    repjur == 136 ~ "Glenwood PD"
    repjur == 137 ~ "Gold Bar PD"
    repjur == 138 ~ "Goldendale PD"
    repjur == 139 ~ "Gonzaga University"
    repjur == 140 ~ "Grand Coulee PD"
    repjur == 141 ~ "Grandview PD"
    repjur == 142 ~ "Granger PD"
    repjur == 143 ~ "Granite Falls PD"
    repjur == 144 ~ "Hamilton PD"
    repjur == 145 ~ "Harrah PD"
    repjur == 146 ~ "Yakima County"
    repjur == 147 ~ "Harrington PD"
    repjur == 148 ~ "Hartline PD"
    repjur == 149 ~ "Hatton PD"
    repjur == 150 ~ "Hoquiam PD"
    repjur == 151 ~ "Hunts Point PD"
    repjur == 152 ~ "Ilwaco PD"
    repjur == 153 ~ "Index PD"
    repjur == 154 ~ "Ione PD"
    repjur == 155 ~ "Issaquah PD"
    repjur == 156 ~ "Kahlotus PD"
    repjur == 157 ~ "Kalama PD"
    repjur == 158 ~ "Kelso PD"
    repjur == 159 ~ "Kennewick PD"
    repjur == 160 ~ "Kent PD"
    repjur == 161 ~ "Kettle Falls PD"
    repjur == 162 ~ "King Co Airport PD"
    repjur == 163 ~ "Kirkland PD"
    repjur == 164 ~ "Kittitas PD"
    repjur == 165 ~ "Klickitat PD"
    repjur == 166 ~ "Krupp PD"
    repjur == 167 ~ "La Center PD"
    repjur == 168 ~ "La Conner PD"
    repjur == 169 ~ "Lacey PD"
    repjur == 170 ~ "Lacrosse PD"
    repjur == 171 ~ "Lake Forest Park PD"
    repjur == 172 ~ "Lake Stevens PD"
    repjur == 173 ~ "Lakewood PD"
    repjur == 174 ~ "Lamon PD"
    repjur == 175 ~ "Langley PD"
    repjur == 176 ~ "Latah PD"
    repjur == 177 ~ "Leavenworth PD"
    repjur == 178 ~ "Lind PD"
    repjur == 179 ~ "Long Beach PD"
    repjur == 180 ~ "Longview PD"
    repjur == 181 ~ "Lyle PD"
    repjur == 182 ~ "Lyman PD"
    repjur == 183 ~ "Lynden PD"
    repjur == 184 ~ "Lynnwood PD"
    repjur == 185 ~ "Mabton PD"
    repjur == 186 ~ "Malden PD"
    repjur == 187 ~ "Mansfield City Hall"
    repjur == 188 ~ "Maple Valley PD"
    repjur == 189 ~ "Marysville PD"
    repjur == 190 ~ "Mattawa PD"
    repjur == 191 ~ "McCleary PD"
    repjur == 192 ~ "Medical Lake PD"
    repjur == 193 ~ "Medina PD"
    repjur == 194 ~ "Mercer Isl Dept Pub"
    repjur == 195 ~ "Mesa PD"
    repjur == 196 ~ "Metaline Falls PD"
    repjur == 197 ~ "Mill Creek PD"
    repjur == 198 ~ "Millwood PD"
    repjur == 199 ~ "Milton PD"
    repjur == 200 ~ "Monroe PD"
    repjur == 201 ~ "Montesano PD"
    repjur == 202 ~ "Morton PD"
    repjur == 203 ~ "Moses Lake PD"
    repjur == 204 ~ "Mossyrock PD"
    repjur == 205 ~ "Mount Vernon PD"
    repjur == 206 ~ "Mountlake PD"
    repjur == 207 ~ "Moxee PD"
    repjur == 208 ~ "Mukilteo PD"
    repjur == 209 ~ "Naches PD"
    repjur == 210 ~ "Napavine PD"
    repjur == 211 ~ "Newport PD"
    repjur == 212 ~ "Nooksack PD"
    repjur == 213 ~ "Normandy Park PD"
    repjur == 214 ~ "North Bend PD"
    repjur == 215 ~ "N Bonneville PD"
    repjur == 216 ~ "Northport PD"
    repjur == 217 ~ "Oak Harbor PD"
    repjur == 218 ~ "Oakville PD"
    repjur == 219 ~ "Ocean Shores PD"
    repjur == 220 ~ "Odessa PD"
    repjur == 221 ~ "Okanogan PD"
    repjur == 222 ~ "Olympia PD"
    repjur == 223 ~ "Omak PD"
    repjur == 224 ~ "Oroville PD"
    repjur == 225 ~ "Orting PD"
    repjur == 226 ~ "Othello PD"
    repjur == 227 ~ "Pacific PD"
    repjur == 228 ~ "Palouse PD"
    repjur == 229 ~ "Pasco PD"
    repjur == 230 ~ "Pe Ell PD"
    repjur == 231 ~ "Pomeroy PD"
    repjur == 232 ~ "Port Angeles PD"
    repjur == 233 ~ "Port Of Pasco PD"
    repjur == 234 ~ "Port Of Seattle PD"
    repjur == 235 ~ "Port Of Tacoma PD"
    repjur == 236 ~ "Port Orchard PD"
    repjur == 237 ~ "Port Townsend PD"
    repjur == 238 ~ "Poulsbo PD"
    repjur == 239 ~ "Prescott PD"
    repjur == 240 ~ "Prosser PD"
    repjur == 241 ~ "Pullman PD"
    repjur == 242 ~ "Puyallup PD"
    repjur == 243 ~ "Quincy PD"
    repjur == 244 ~ "Ranier PD"
    repjur == 245 ~ "Raymond PD"
    repjur == 246 ~ "Reardan PD"
    repjur == 247 ~ "Redmond PD"
    repjur == 248 ~ "Renton PD"
    repjur == 249 ~ "Republic PD"
    repjur == 250 ~ "Richland PD"
    repjur == 251 ~ "Ridgefield PD"
    repjur == 252 ~ "Ritzville PD"
    repjur == 253 ~ "Riverside PD"
    repjur == 254 ~ "Rock Island PD"
    repjur == 255 ~ "Rockford PD"
    repjur == 256 ~ "Roosevelt PD"
    repjur == 257 ~ "Rosalia PD"
    repjur == 258 ~ "Roslyn PD"
    repjur == 259 ~ "Roy PD"
    repjur == 260 ~ "Royal City PD"
    repjur == 261 ~ "Ruston PD"
    repjur == 262 ~ "Seatac PD"
    repjur == 263 ~ "Seattle PD"
    repjur == 264 ~ "Seattle Univ Pub Saf"
    repjur == 265 ~ "Sedro Woolley PD"
    repjur == 266 ~ "Selah PD"
    repjur == 267 ~ "Sequim PD"
    repjur == 268 ~ "Shelton PD"
    repjur == 269 ~ "Shoreline PD"
    repjur == 270 ~ "Skykomish PD"
    repjur == 271 ~ "Snohomish PD"
    repjur == 272 ~ "Soap Lake PD"
    repjur == 273 ~ "South Bend PD"
    repjur == 274 ~ "S Cle Elum PD"
    repjur == 275 ~ "South Prarie PD"
    repjur == 276 ~ "Spangle PD"
    repjur == 277 ~ "Spokane Airport PD"
    repjur == 278 ~ "Spokane PD"
    repjur == 279 ~ "Sprague PD"
    repjur == 280 ~ "Springdale PD"
    repjur == 281 ~ "St John PD"
    repjur == 282 ~ "Stanwood PD"
    repjur == 283 ~ "Starbuck PD"
    repjur == 284 ~ "Steilacoom Dpt Pub S"
    repjur == 285 ~ "Stevenson PD"
    repjur == 286 ~ "Sultan PD"
    repjur == 287 ~ "Sumas PD"
    repjur == 288 ~ "Sumner PD"
    repjur == 289 ~ "Sunnyside PD"
    repjur == 290 ~ "Tacoma PD"
    repjur == 291 ~ "Tekoa PD"
    repjur == 292 ~ "Tenino PD"
    repjur == 293 ~ "Tieton PD"
    repjur == 294 ~ "Toledo PD"
    repjur == 295 ~ "Tonasket PD"
    repjur == 296 ~ "Toppenish PD"
    repjur == 297 ~ "Tukwila PD"
    repjur == 298 ~ "Tumwater PD"
    repjur == 299 ~ "Twisp PD"
    repjur == 300 ~ "Union Gap PD"
    repjur == 301 ~ "Uniontown PD"
    repjur == 302 ~ "Univ Of WA PD"
    repjur == 303 ~ "University Place PD"
    repjur == 304 ~ "Vader PD"
    repjur == 305 ~ "Vancouver PD"
    repjur == 306 ~ "Waitsburg PD"
    repjur == 307 ~ "Walla Walla PD"
    repjur == 308 ~ "Wapato PD"
    repjur == 309 ~ "Warden PD"
    repjur == 310 ~ "WA State Univ PD"
    repjur == 311 ~ "Washougal PD"
    repjur == 312 ~ "Washtucna PD"
    repjur == 313 ~ "Waterville PD"
    repjur == 314 ~ "Waverly PD"
    repjur == 315 ~ "Wenatchee PD"
    repjur == 316 ~ "W Richland PD"
    repjur == 317 ~ "Western WA Univ PD"
    repjur == 318 ~ "Westport PD"
    repjur == 319 ~ "White Salmon PD"
    repjur == 320 ~ "Wilbur PD"
    repjur == 321 ~ "Wilkeson Marshal"
    repjur == 322 ~ "Wilson Creek PD"
    repjur == 323 ~ "Winlock PD"
    repjur == 324 ~ "Winthrop Marshal"
    repjur == 325 ~ "Wishram PD"
    repjur == 326 ~ "Woodinville PD"
    repjur == 327 ~ "Woodland PD"
    repjur == 328 ~ "Woodway PD"
    repjur == 329 ~ "City Of Yacolt"
    repjur == 330 ~ "Yakima PD"
    repjur == 331 ~ "Yarrow Point PD"
    repjur == 332 ~ "Yelm PD"
    repjur == 333 ~ "Zillah PD"
    repjur == 334 ~ "Colville Tribal PD"
    repjur == 335 ~ "Makah Tribal PD"
    repjur == 336 ~ "Seattle PD Records"
    repjur == 337 ~ "Bellingham PD"
    repjur == 338 ~ "Anacortes Police Dept"
    repjur == 339 ~ "Spokane Valley PD"
    repjur == 340 ~ "WA Dept Of Natural Resources"
    repjur == 341 ~ "Colville PD"
    repjur == 342 ~ "Quinault Tribal PD"
    repjur == 343 ~ "None"
    repjur == 344 ~ "Yakama Nation PD"
    repjur == 345 ~ "Spokane Tribal PD"
    repjur == 346 ~ "Liberty Lake PD"
    repjur == 347 ~ "Shoalwater Bay Tribal PD"
    repjur == 348 ~ "Kenmore PD"
  ))